version: 2

project_name: go-better-html-coverage

before:
  hooks:
    - go mod tidy

builds:
  - id: go-better-html-coverage
    main: ./main.go
    binary: go-better-html-coverage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  draft: false
  prerelease: auto
  make_latest: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: go-better-html-coverage
    repository:
      owner: chmouel
      name: lazyworktree
    directory: Casks
    commit_author:
      name: goreleaserbot
      email: goreleaser@chmouel.com
    homepage: "https://github.com/chmouel/go-better-html-coverage"
    description: "Better HTML Go Coverage - Single-file HTML coverage reports for Go"
    license: Apache-2.0
    caveats: |
      On first run, macOS may block the binary. To remove the quarantine attribute:
        xattr -d com.apple.quarantine #{staged_path}/lazyworktree

aurs:
  - name: go-better-html-coverage-bin
    git_url: ssh://aur@aur.archlinux.org/go-better-html-coverage-bin.git
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@chmouel.com
    optdepends:
      - xdg-utils
    homepage: "https://github.com/chmouel/go-better-html-coverage"
    description: "Better HTML Go Coverage - Single-file HTML coverage reports for Go"
    license: Apache-2.0
