# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-better-html-coverage" do
  name "go-better-html-coverage"
  desc "A better HTML Go Coverage - Single-file HTML coverage reports for Go"
  homepage "https://github.com/chmouel/go-better-html-coverage"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-better-html-coverage"

  on_macos do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-amd64.tar.gz"
      sha256 "2182040e3ef6b0bad4a488eefd77bcbe0e5d9ef47c9ed86853db5ac83dff46eb"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-arm64.tar.gz"
      sha256 "0aadd24516d16acecec64729936f3d2ed2c55f9ce4dd2eb4e7b8a76a545159bc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-amd64.tar.gz"
      sha256 "8068b4dfea6172de1025c541cb3a143d9819d145be7a2f4ef434edfb6c31804a"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-arm64.tar.gz"
      sha256 "a02fd35edfb8c06c0eb71de2e8d632147b61c05b1628d7c687059c477bed8451"
    end
  end

  caveats do
    "On first run, macOS may block the binary. To remove the quarantine attribute:"
    "  xattr -d com.apple.quarantine #{staged_path}/go-better-html-coverage"
  end

  # No zap stanza required
end
