# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-better-html-coverage" do
  name "go-better-html-coverage"
  desc "Better HTML Go Coverage - Single-file HTML coverage reports for Go"
  homepage "https://github.com/chmouel/go-better-html-coverage"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-better-html-coverage"

  on_macos do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-amd64.tar.gz"
      sha256 "ea9297af0fb1c97c43050c698fbe0634f6ba53de17fc129fbfffd66a8be3d3e2"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-arm64.tar.gz"
      sha256 "6a54535a74a1fcd3015b3b996c832b9cbde64c704cc94a755ea4c3cd2fcabf39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-amd64.tar.gz"
      sha256 "dad382ebb4e316d0a465513e413839787ee9f3917c3ae6260d105339b90bd4c8"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-arm64.tar.gz"
      sha256 "6dbc226b25ead4067030d775120b3781b140f29186266ed798540fe63aac2238"
    end
  end

  caveats do
    "On first run, macOS may block the binary. To remove the quarantine attribute:"
    "  xattr -d com.apple.quarantine #{staged_path}/go-better-html-coverage"
  end

  # No zap stanza required
end
