# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-better-html-coverage" do
  name "go-better-html-coverage"
  desc "Better HTML Go Coverage - Single-file HTML coverage reports for Go"
  homepage "https://github.com/chmouel/go-better-html-coverage"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-better-html-coverage"

  on_macos do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-amd64.tar.gz"
      sha256 "9222804d414d71c9df03ece9a2fa5088891ca3a7a1af696e27ab5deb3840bd15"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-darwin-arm64.tar.gz"
      sha256 "e72ea74a42f005558853a9e01c89760e34a29cead6e7186928655319d35eba88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-amd64.tar.gz"
      sha256 "bd2b00ac7bc52017e24783b74c8b31ef0370a27ae4a2113888d358ce29e2b873"
    end
    on_arm do
      url "https://github.com/chmouel/go-better-html-coverage/releases/download/v#{version}/go-better-html-coverage-#{version}-linux-arm64.tar.gz"
      sha256 "b24114d9ed3e14beaee5b35ffd8795546caf0788692e12e34ff0c3ddfe9e6c11"
    end
  end

  caveats do
    "On first run, macOS may block the binary. To remove the quarantine attribute:"
    "  xattr -d com.apple.quarantine #{staged_path}/go-better-html-coverage"
  end

  # No zap stanza required
end
